export enum UserRole {
  CUSTOMER = "CUSTOMER",
  ARTISAN = "ARTISAN",
  GUILD_MASTER = "GUILD_MASTER",
  ADMIN = "ADMIN",
}

export enum GuildTier {
  APPRENTICE = "APPRENTICE",
  JOURNEYMAN = "JOURNEYMAN",
  MASTER = "MASTER",
}

export enum ServiceCategory {
  ELECTRICAL = "ELECTRICAL",
  PLUMBING = "PLUMBING",
  CARPENTRY = "CARPENTRY",
  APPLIANCE_REPAIR = "APPLIANCE_REPAIR",
  HVAC_AC = "HVAC_AC",
  LOCKSMITH = "LOCKSMITH",
  EMERGENCY_SOS = "EMERGENCY_SOS",
}

export enum BookingStatus {
  PENDING_TRIAGE = "PENDING_TRIAGE",
  DISPATCHED = "DISPATCHED",
  ON_SITE = "ON_SITE",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  DISPUTED = "DISPUTED",
  CANCELLED = "CANCELLED",
}

export enum EscrowStatus {
  HELD = "HELD",
  RELEASED = "RELEASED",
  REFUNDED = "REFUNDED",
  DISPUTED = "DISPUTED",
}

export enum PanchayatVerdict {
  PENDING = "PENDING",
  WORKER_UPHELD = "WORKER_UPHELD",
  CUSTOMER_REFUNDED = "CUSTOMER_REFUNDED",
}
